### ISSUE TITLE
Filter form doesn't work with accented characters

### ISSUE THREAD

**Issue by douglascrp** [deas/contentreich-alfresco-datalists#34] opened 2015-07-21 03:30 UTC
I've just found out that this function is messing with my parameters :

```
onFilterFormSubmit: function ExtDataGrid_onFilterFormSubmit(){
    	  //alert(this.formsRuntime.getFormData());
    	  YAHOO.Bubbling.fire("changeFilter",
          {
             filterOwner: this.id,
             filterId: "filterform",
             filterData: Alfresco.util.toQueryString(this.formsRuntime.getFormData())
          });
      },
```
This code is into the file /fme-alfresco-extdl-share/src/main/resources/META-INF/components/data-lists/extended-datagrid.js

```
this.formsRuntime.getFormData()
```
 gets the form data correctly, like:
prop_lab_doenca:"Doença Não Ocupacional"

but when 
```
Alfresco.util.toQueryString(this.formsRuntime.getFormData())
```
 executes, the result is:
prop_lab_doenca=Doen%C3%A7a%20N%C3%A3o%20Ocupacional

This odd value of "Doen%C3%A7a%20N%C3%A3o%20Ocupacional" completely breaks the filter.

@deas Do you know if it is possible to control the Alfresco.util.toQueryString() function to avoid this problem?

**Comment by douglascrp** [comment] 2015-07-21 03:49
Things get even worst when the form is updated to reflect the filter values in the controls:
```
var filterData =  Alfresco.util.getQueryStringParameters(this.currentFilter.filterData);
```
At this point, the value is different:
prop_lab_doenca=DoenÃ§a NÃ£o Ocupacional

It seems to be a problem with Alfresco.util.toQueryString and Alfresco.util.getQueryStringParameters

**Comment by douglascrp** [comment] 2015-07-21 04:23
@deas I've just discovered it works well on Chrome.
This problem happens only with Firefox.

**Comment by davidcognite** [comment] 2015-07-21 15:24
I'm not sure it is a problem with either of those util methods. They effectively wrap the native encodeURIComponent/decodeURIComponent methods, so you should be able to get out exactly what you put in.

**Comment by douglascrp** [comment] 2015-07-21 15:34
@davidcognite the Alfresco.util.toQueryString seems to be right, as it's encoding the value using utf8.
But I can't get the original value when executing the Alfresco.util.getQueryStringParameters.
I'll keep trying tonight.
Thank you.

**Comment by AFaust** [comment] 2015-07-21 16:45
@douglascrp I encountered similar issues in the past where behaviour of Firefox seemed different than other browsers, but most of the time it turned out not to be an issue with the frontend, but with the backend where some code messed up the request character encoding and thus caused logic to fail.
In your case, %C3%A3 is a perfectly valid UTF-8 character encoding for ã - and actually, any browser that does not encode it this way is probably using a different encoding than UTF-8 (e.g. ISO-8859-1).
Most likely, the error here is in the backend which does not correctly evaluate that encoded character and thus generates an incorrect FTS query.

1) Check your URIEncoding on the Tomcat <connector> Element - this should always be set to UTF-8
2) Check any installed addons for code that retrieves URL fragments or request body from HttpServletRequest without doing a check & sensible default first, like this:

if (req.getCharacterEncoding() == null)
{
      req.setCharacterEncoding("UTF-8");
}

In a couple of instances where I encountered such behaviour, the error could be tracked down to a custom servlet filter, i.e. for custom authentication or context setup.

**Comment by douglascrp** [comment] 2015-07-21 18:09
@AFaust Thank you for the tips.
I'm going to try them tonight.

**Comment by douglascrp** [comment] 2015-07-22 05:43
@AFaust I tried your tips.
I've checked, and all the Connectors were already configured to use UTF-8, with the parameter URIEncoding="UTF-8"
I also tried to include the parameter useBodyEncodingForURI="true"
Those configs are in server.xml file.

I tried the addon using those configs, and it still didn't work.

After that, i also tried to configure the filters define here http://tomcat.apache.org/tomcat-7.0-doc/config/filter.html#Add_Default_Character_Set_Filter
and here http://tomcat.apache.org/tomcat-7.0-doc/config/filter.html#Set_Character_Encoding_Filter

Again, it didn't work

**Comment by douglascrp** [comment] 2015-07-28 12:53
I've solved my problem by using a localized constraint on my custom data-list.
It gave me other limitations, but I can at least use it now.

**Comment by deas** [comment] 2015-08-11 10:39
The issue is hitting me know. For me, Firefox (using 39.0.3) breaks characters which have a different representation in UTF-8 than they have in ISO-8859-1. Things works fine in Chrome. The extension does not mess with character sets at all, so I guess the root cause is somewhere in utility code shipping with alfresco.

**Comment by douglascrp** [comment] 2015-08-11 15:06
@deas After all the tests I did, I have to agree with you.

**Comment by deas** [comment] 2015-08-11 15:25
Turned out `datagrid.js` uses `window.escape` which is  deprecated and seems to assume latin1 characters on Firefox. The issue should actually be fixed in Share and not in this extension. Share may have other similar  issues. At least `documentlist.js` also has window.escape calls in 5.0.d.

**Closed by deas** 2015-08-11 15:25 UTC

**Comment by deas** [comment] 2015-08-12 09:49
In fact the encoding mess we see here is a looks a little more complicated.

Submitting "ä"  with Chrome, we end up in `_setupHistoryManagers` from `datagrid.js` with
`filters[1] = "%3Fprop_dl_contactFirstName%3D%25C3%25A4%26..."`. Both, `window.unescape` and `decodeURIComponent` give `"?prop_dl_contactFirstName=%C3%A4&..."` which works fine.

In Firefox, we get `filters[1] = "?prop_dl_contactFirstName=%C3%A4&..."`. `window.unescape` breaks that  giving `"?prop_dl_contactFirstName=Ã¤&..."` while `decodeURIComponent` yields `"?prop_dl_contactFirstName=ä&..."` which is at least handled  properly futher on.

At the end of the day it seems the symptoms rarely show up and there is a lot of old and deprecated code (YUI)  involved. Finally the fix gets rid of the symptoms so I'll leave this as is now. Nevertheless, I'll raise an issue at Alfrescos JIRA since they might want to look at it.
